### ISSUE TITLE
May I ask why this error occurred

### ISSUE THREAD

**Issue by xiaobai1086** [walker-hyf/ECSS#4]
tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Device of CompTransTTS: cuda
Traceback (most recent call last):
  File "synthesize.py", line 218, in <module>
    synthesize(device, model, args, configs, vocoder, batchs, control_values)
  File "synthesize.py", line 67, in synthesize
    output = model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/lanyun-tmp/ECSS/model/CompTransTTS.py", line 211, in forward
    for j in range(data["audio"].x.shape[0]):
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/storage.py", line 96, in __getattr__
    raise AttributeError(
AttributeError: 'NodeStorage' object has no attribute 'x'

**Comment by 5Hyeons** [comment]
https://github.com/walker-hyf/ECSS/blob/c1545fdb12ca56482de4ff3550dc47b81d9fe794/utils/tools.py#L202
I think this line should be commented out. then it works
